import { c as create_ssr_component, v as validate_component } from "../../chunks/index2.js";
/* empty css                  */import Page from "./Header/_page.svelte.js";
import Page$5 from "./footer/_page.svelte.js";
import Page$2 from "./about/_page.svelte.js";
import Page$1 from "./titleName/_page.svelte.js";
import Page$3 from "./projects/_page.svelte.js";
import Page$4 from "./contact/_page.svelte.js";
const app = "";
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<div class="${"app"}" id="${"app"}"><div class="${"feather2 tooltip"}"><span class="${"tooltiptext"}">The artwork you&#39;ve seen throughout the project has been generated by AI using an excellent tool called Midjourney. </span></div>
	<div class="${"mouseDown"}"></div>
	<div class="${"cursor"}"><div class="${"clickAnimation"}"><div class="${"shape feather small"}"></div>
			<div class="${"shape feather big"}"></div></div></div>
	${validate_component(Page, "HeaderData").$$render($$result, {}, {}, {})}
	${validate_component(Page$1, "TitleData").$$render($$result, {}, {}, {})}
	${validate_component(Page$2, "AboutData").$$render($$result, {}, {}, {})}
	${validate_component(Page$3, "ProjectData").$$render($$result, {}, {}, {})}
	${validate_component(Page$4, "ContactData").$$render($$result, {}, {}, {})}
	${validate_component(Page$5, "FooterData").$$render($$result, {}, {}, {})}</div>`;
});
export {
  Layout as default
};
