<script lang="ts">
	import '../app.postcss';
	import '../style.css';
	import { onMount } from 'svelte';
	import toggleText from './toggleButton';
	import HeaderData from './Header/+page.svelte';
	import FooterData from './footer/+page.svelte';
	import AboutData from './about/+page.svelte';
	import TitleData from './titleName/+page.svelte';
	import ProjectData from './projects/+page.svelte';
	import ContactData from './contact/+page.svelte';
	onMount(toggleText);

</script>

<div class="app" id="app">
	<div class="feather2 tooltip"><span class="tooltiptext">The artwork you've seen throughout the project has been generated by AI using an excellent tool called Midjourney. </span></div>
	<div class="mouseDown"></div>
	<div class="cursor">
		<div class="clickAnimation">
			<div class="shape feather small" ></div>
			<div class="shape feather big"></div>
		</div>
	</div>
	<HeaderData />
	<TitleData />
	<AboutData />
	<ProjectData />
	<ContactData />
	<FooterData />

</div>
